server:
  port: 8080
spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/micro_department_db
    username: root
    password: water786
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    ddl-auto: update


eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
